export default {
  storages: ["SQL"],
  default: "Child Entity",
  $schema: "http://json-schema.org/draft-07/schema",
  id: "Child",
  title: "Child Entity",
  type: "object",
  properties: {
    StringFieldSingle: {
      storages: ["SQL"],
      nullable: true,
      description: "String Field Single",
      readOnly: false,
      versionable: false,
      id: "CE_Child_StringFieldSingle",
      title: "Child.StringFieldSingle",
      type: "string",
      maxLength: 255,
    },
    BooleanFieldSingle: {
      storages: ["SQL"],
      default: "false",
      nullable: true,
      description: "Boolean Field Single",
      readOnly: false,
      versionable: false,
      id: "CE_Child_BooleanFieldSingle",
      title: "Child.BooleanFieldSingle",
      type: "string",
    },
    DateFieldSingle: {
      storages: ["SQL"],
      nullable: true,
      format: "date-time",
      description: "Date Field Single",
      readOnly: false,
      versionable: false,
      id: "CE_Child_DateFieldSingle",
      title: "Child.DateFieldSingle",
      type: "string",
    },
  },
};
