export default class DemoEntity {
  code = "Demo";
  label = "Demo";
  schema = {
    storages: [],
    default: "Demo for generating Web App from module",
    $schema: "http://json-schema.org/draft-07/schema",
    id: "Demo",
    title: "Demo",
    type: "object",
    properties: {
      firstName: {
        storages: [],
        nullable: false,
        minLength: 1,
        description: "First name",
        readOnly: false,
        versionable: false,
        id: "CE_Demo_firstName",
        title: "Demo.firstName",
        type: "string",
        maxLength: 255,
      },
      lastName: {
        storages: [],
        nullable: false,
        minLength: 1,
        description: "Last name",
        readOnly: false,
        versionable: false,
        id: "CE_Demo_lastName",
        title: "Demo.lastName",
        type: "string",
        maxLength: 255,
      },
      gender: {
        storages: [],
        nullable: true,
        description: "Gender",
        readOnly: false,
        versionable: false,
        id: "CE_Demo_gender",
        title: "Demo.gender",
        enum: ["other", "female", "male"],
      },
      birthDate: {
        storages: [],
        nullable: true,
        format: "date-time",
        description: "Birth date",
        readOnly: false,
        versionable: false,
        id: "CE_Demo_birthDate",
        title: "Demo.birthDate",
        type: "string",
      },
    },
    required: ["firstName", "lastName"],
  };
  refSchemas = [];
  formFields = [
    {
      code: "birthDate",
      description: "Birth date",
      fieldType: "DATE",
      accountLevel: "CE_Demo",
      appliesTo: "CE_Demo",
      useInheritedAsDefaultValue: false,
      storageType: "SINGLE",
      valueRequired: false,
      versionable: false,
      triggerEndPeriodEvent: false,
      listValues: {},
      allowEdit: true,
      hideOnNew: false,
      contentTypes: [],
      fileExtensions: [],
      saveOnExplorer: false,
      guiPosition: "tab:Demo:0;field:3",
      identifier: false,
      storages: [],
      samples: [],
      summary: false,
      audited: false,
      persisted: true,
      filter: false,
      unique: false,
      matrixColumns: [],
    },
    {
      code: "firstName",
      description: "First name",
      fieldType: "STRING",
      accountLevel: "CE_Demo",
      appliesTo: "CE_Demo",
      useInheritedAsDefaultValue: false,
      storageType: "SINGLE",
      valueRequired: true,
      versionable: false,
      triggerEndPeriodEvent: false,
      listValues: {},
      allowEdit: true,
      hideOnNew: false,
      maxValue: 255,
      contentTypes: [],
      fileExtensions: [],
      saveOnExplorer: false,
      guiPosition: "tab:Demo:0;field:0",
      identifier: false,
      storages: [],
      samples: [],
      summary: false,
      audited: false,
      persisted: true,
      filter: false,
      unique: false,
      matrixColumns: [],
    },
    {
      code: "gender",
      description: "Gender",
      fieldType: "LIST",
      accountLevel: "CE_Demo",
      appliesTo: "CE_Demo",
      useInheritedAsDefaultValue: false,
      storageType: "SINGLE",
      valueRequired: false,
      versionable: false,
      triggerEndPeriodEvent: false,
      listValues: {
        female: "Female",
        male: "Male",
        other: "Other",
      },
      allowEdit: true,
      hideOnNew: false,
      contentTypes: [],
      fileExtensions: [],
      saveOnExplorer: false,
      guiPosition: "tab:Demo:0;field:2",
      identifier: false,
      storages: [],
      samples: [],
      summary: false,
      audited: false,
      persisted: true,
      filter: false,
      unique: false,
      matrixColumns: [],
    },
    {
      code: "lastName",
      description: "Last name",
      fieldType: "STRING",
      accountLevel: "CE_Demo",
      appliesTo: "CE_Demo",
      useInheritedAsDefaultValue: false,
      storageType: "SINGLE",
      valueRequired: true,
      versionable: false,
      triggerEndPeriodEvent: false,
      listValues: {},
      allowEdit: true,
      hideOnNew: false,
      maxValue: 255,
      contentTypes: [],
      fileExtensions: [],
      saveOnExplorer: false,
      guiPosition: "tab:Demo:0;field:1",
      identifier: false,
      storages: [],
      samples: [],
      summary: false,
      audited: false,
      persisted: true,
      filter: false,
      unique: false,
      matrixColumns: [],
    },
  ];
  endpoints = {
    DETAIL: {
      schema: null,
      override: null,
    },
    LIST: {
      schema: null,
      override: null,
    },
    NEW: {
      schema: null,
      override: null,
    },
    UPDATE: {
      schema: null,
      override: null,
    },
  };
}
